micronaut:
  application:
    name: partnersServices
  server:
    cors:
      enabled: true

#tag::datasources[]
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
#end::datasources[]
jpa:
  default:
    entity-scan:
      packages: 'com.peraton.ymca.referral'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false

#tag::security[]
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: testChangeMeForAMuchSaferPasswordOtherwiseItseasilyhackable
#end::security[]
#tag::refresh[]
---
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: testChangeMeForAMuchSaferPasswordOtherwiseItseasilyhackable
#end::refresh[]
    endpoints:
      logout:
        enabled: true